version: "3"
services:
  export-service:
    image: export-service
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - mysqldb
    environment: 
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/fileDb?useSSL=false&allowPublicKeyRetrieval=true
         
  mysqldb: 
    image: mysql:8
    environment:
      MYSQL_DATABASE: fileDb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always