spring: 
  datasource: 
      url: jdbc:mysql://mysqldb:3306/fileDb?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      platform: mysql
      initialization-mode: always

  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate: 
      ddl-auto: update

  servlet:  
   multipart: 
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
      
      
server: 
  servlet: 
    context-path: /api/importService/v1     

